(WIP) Feat book shop
cloudwego/biz-demo pull request #24
Opened 2023-01-24 06:18 UTC by bodhisatan

#### What type of PR is this?

#### What this PR does / why we need it (en: English/zh: Chinese):

en: 
zh:

#### Which issue(s) this PR fixes:

2023-01-25 16:05 UTC, li-jin-gou requested changes
use hz and idl to init api and add introduce to readme.md

2023-01-25 16:23 UTC, li-jin-gou commented on book-shop/app/item/infras/repository/init.go
> +	m := DB.Migrator()
use `docker` init sql instead of migrate

2023-01-25 16:26 UTC, li-jin-gou commented on book-shop/go.mod
> +	github.com/bwmarrin/snowflake v0.3.0
I think we could use more extensions to improve the system such as otel、gzip、pprof

2023-01-28 03:18 UTC, GuangmingLuo commented on book-shop/go.mod
> +require (
merge to one

2023-01-28 03:21 UTC, GuangmingLuo commented on book-shop/idl/item.thrift
> +    Delete, // 删除
显示逗号的格式不太对

2023-01-28 03:21 UTC, GuangmingLuo commented on book-shop/idl/item.thrift
> +    Delete, // 删除
其它IDL文件也有类似问题

2023-01-28 03:25 UTC, GuangmingLuo commented
1. 注意相关文件需要添加 license header，生成代码添加到 [path ignore](https://github.com/cloudwego/biz-demo/blob/main/.licenserc.yaml)
2. 在根目录 readme 添加子项目说明以及 maintainer

2023-01-28 07:35 UTC, GuangmingLuo commented on book-shop/go.mod
> +	github.com/kitex-contrib/registry-etcd v0.0.0-20221223084757-0d49e7162359
you may use https://github.com/kitex-contrib/registry-etcd/releases/tag/v0.1.0 using etcd/server v3.5.7

2023-01-28 09:08 UTC, GuangmingLuo commented on book-shop/go.mod
> +	github.com/cloudwego/kitex v0.4.3
update to the latest version: Hertz 0.5.1, Kitex 0.4.4

2023-01-29 08:55 UTC, li-jin-gou approved these changes

2023-01-29 08:56 UTC, li-jin-gou commented
LGTM

2023-01-29 08:56 UTC, merged